//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubanFM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoubanFM.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string AccountTab {
            get {
                return ResourceManager.GetString("AccountTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string AlbumInfoPage {
            get {
                return ResourceManager.GetString("AlbumInfoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include album title..
        /// </summary>
        public static string AlbumSearchCheckBox {
            get {
                return ResourceManager.GetString("AlbumSearchCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application will be shut down.
        /// </summary>
        public static string ApplicationWillClose {
            get {
                return ResourceManager.GetString("ApplicationWillClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto login.
        /// </summary>
        public static string AutoLoginCheckBox {
            get {
                return ResourceManager.GetString("AutoLoginCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available after login.
        /// </summary>
        public static string AvailableAfterLoginBorder {
            get {
                return ResourceManager.GetString("AvailableAfterLoginBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string BottomAlignment {
            get {
                return ResourceManager.GetString("BottomAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply now.
        /// </summary>
        public static string BtnApplyProxy {
            get {
                return ResourceManager.GetString("BtnApplyProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string BtnScaleTransformReset {
            get {
                return ResourceManager.GetString("BtnScaleTransformReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string CbAutoForeground {
            get {
                return ResourceManager.GetString("CbAutoForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop lyrics.
        /// </summary>
        public static string CbEnableDesktopLyrics {
            get {
                return ResourceManager.GetString("CbEnableDesktopLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded lyrics.
        /// </summary>
        public static string CbEnableEmbeddedLyrics {
            get {
                return ResourceManager.GetString("CbEnableEmbeddedLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Baidu Ting.
        /// </summary>
        public static string CbSearchBaiduTing {
            get {
                return ResourceManager.GetString("CbSearchBaiduTing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Google Music.
        /// </summary>
        public static string CbSearchGoogleMusic {
            get {
                return ResourceManager.GetString("CbSearchGoogleMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable lyrics.
        /// </summary>
        public static string CbShowLyrics {
            get {
                return ResourceManager.GetString("CbShowLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show lyrics border to help adjust layout..
        /// </summary>
        public static string CbShowLyricsBackground {
            get {
                return ResourceManager.GetString("CbShowLyricsBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string CenterAlignment {
            get {
                return ResourceManager.GetString("CenterAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        public static string ChannelsTab {
            get {
                return ResourceManager.GetString("ChannelsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust volume with mouse wheel..
        /// </summary>
        public static string CheckBoxAdjustVolumeWithMouseWheel {
            get {
                return ResourceManager.GetString("CheckBoxAdjustVolumeWithMouseWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always show tray icon.
        /// </summary>
        public static string CheckBoxAlwaysShowNotifyIcon {
            get {
                return ResourceManager.GetString("CheckBoxAlwaysShowNotifyIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove search results that can not be played..
        /// </summary>
        public static string CheckBoxIsSearchFilterEnabled {
            get {
                return ResourceManager.GetString("CheckBoxIsSearchFilterEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open album info when cover is clicked..
        /// </summary>
        public static string CheckBoxOpenAlbumInfoWhenClickCover {
            get {
                return ResourceManager.GetString("CheckBoxOpenAlbumInfoWhenClickCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember last played channel..
        /// </summary>
        public static string CheckBoxRememberLastChannel {
            get {
                return ResourceManager.GetString("CheckBoxRememberLastChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on topmost.
        /// </summary>
        public static string CheckBoxTopMost {
            get {
                return ResourceManager.GetString("CheckBoxTopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string CheckforUpdates {
            get {
                return ResourceManager.GetString("CheckforUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results are from music.douban.com..
        /// </summary>
        public static string ConsistentResultsLabel {
            get {
                return ResourceManager.GetString("ConsistentResultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share (click this to copy the URL).
        /// </summary>
        public static string CopyUrlButton {
            get {
                return ResourceManager.GetString("CopyUrlButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DJ.
        /// </summary>
        public static string DJRadioRB {
            get {
                return ResourceManager.GetString("DJRadioRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Search&apos; to list all channels..
        /// </summary>
        public static string DJSearchTextBlock {
            get {
                return ResourceManager.GetString("DJSearchTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never play.
        /// </summary>
        public static string DontPlayThumbButton {
            get {
                return ResourceManager.GetString("DontPlayThumbButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DoubanFM official website.
        /// </summary>
        public static string DoubanFMOfficialWebsite {
            get {
                return ResourceManager.GetString("DoubanFMOfficialWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for music downloads..
        /// </summary>
        public static string DownloadSearchButton {
            get {
                return ResourceManager.GetString("DownloadSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Searching Settings.
        /// </summary>
        public static string DownloadSearchSettingsGroupBox {
            get {
                return ResourceManager.GetString("DownloadSearchSettingsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string EmailUserNameBlock {
            get {
                return ResourceManager.GetString("EmailUserNameBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occured.
        /// </summary>
        public static string ExceptionWindowTitle {
            get {
                return ResourceManager.GetString("ExceptionWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to favorites.
        /// </summary>
        public static string FavoriteButton {
            get {
                return ResourceManager.GetString("FavoriteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the mouse to the cover
        ///Surprise for you!.
        /// </summary>
        public static string FirstTimePanelTextBlock {
            get {
                return ResourceManager.GetString("FirstTimePanelTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string GeneralSettingsButton {
            get {
                return ResourceManager.GetString("GeneralSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get play list failed : {0}.
        /// </summary>
        public static string GetPlayListFailedMessage {
            get {
                return ResourceManager.GetString("GetPlayListFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer: This software is a third-party client, not the official DoubanFM client..
        /// </summary>
        public static string HelpWindowParagraphDisclaimer1 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphDisclaimer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string HelpWindowParagraphDisclaimer2 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphDisclaimer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage:.
        /// </summary>
        public static string HelpWindowParagraphDisclaimer3 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphDisclaimer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Web version of the FAQ:.
        /// </summary>
        public static string HelpWindowParagraphDisclaimer4 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphDisclaimer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoubanFM official website:.
        /// </summary>
        public static string HelpWindowParagraphDisclaimer5 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphDisclaimer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DoubanFM Help and Support:.
        /// </summary>
        public static string HelpWindowParagraphDisclaimer6 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphDisclaimer6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to avoid seeing words unclearly when modifying font in UI?.
        /// </summary>
        public static string HelpWindowParagraphFontModification1 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontModification1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can zoom in main window so that the words are easier to read..
        /// </summary>
        public static string HelpWindowParagraphFontModification2 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontModification2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why do I need to reset the settings if I can&apos;t login, in order to continue using this software?.
        /// </summary>
        public static string HelpWindowParagraphFontModification3 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontModification3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to set a font?.
        /// </summary>
        public static string HelpWindowParagraphFontSet {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can set fonts with names in languages other than English..
        /// </summary>
        public static string HelpWindowParagraphFontSet10 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontSet10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The software can utilize multiple fonts at the same time. Most chinese fonts do not looks good with English words. So sometimes an English font set is need. Here is an example:.
        /// </summary>
        public static string HelpWindowParagraphFontSet2 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontSet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 豆瓣电台 豆瓣電台 DoubanFM 1234567.
        /// </summary>
        public static string HelpWindowParagraphFontSet3 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontSet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font settings allows for different fonts with priority differences, seperated by commas (both half-width and full-width comma are taken). A font in the front of fonts has a higher priority. If none of these fonts can display a specific word, system font will be used. Usually English font is in the front and Chinese font is behind. You can type in “Century,华文新魏” to use multiple fonts, instead of selecting from drop down menu. If an Chinese font has a higher priority than an English font, the English font [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpWindowParagraphFontSet4 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontSet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a specified font is not found, it will be ignored..
        /// </summary>
        public static string HelpWindowParagraphFontSet5 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontSet5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From above, You can see that 华文新魏 doesn&apos;t have the glyphs of Traditional Chinese characters. Traditional Chinese characters will be displayed with default font. You can set a third font to avoid this:.
        /// </summary>
        public static string HelpWindowParagraphFontSet6 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontSet6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case insensitive:.
        /// </summary>
        public static string HelpWindowParagraphFontSet7 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontSet7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whitespaces are allowed before and after a font.
        /// </summary>
        public static string HelpWindowParagraphFontSet8 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontSet8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light, SemiLight, SemiBold and Bold can also be added after the font to force to a specified weight. So that adjusting weight will not affect this font. (Some fonts may not have variety of weights. Usually there are only two weights for Chinese fonts and some English fonts. Others can have many kind of weights. i.e. Segoe UI supports Light, SemiBold and Bold, but not SemiLight)..
        /// </summary>
        public static string HelpWindowParagraphFontSet9 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontSet9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why is it that when I&apos;m already logged in and &apos;Auto login&apos; is checked, it will not login automatically in the next time I run this software?.
        /// </summary>
        public static string HelpWindowParagraphLogin1 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphLogin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usually It&apos;s because you logged out through a browser. You can be logged out for many reasons. Such as using multiple browser to login, then you logged out through one of these browsers. You will be logged out in other browsers automatically. In this software too. Try to avoid logging out at any place..
        /// </summary>
        public static string HelpWindowParagraphLogin2 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphLogin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to.
        /// </summary>
        public static string HelpWindowParagraphOpenBrowser1 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphOpenBrowser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and login. Check if your account has an unnormal state, like locked or not activated..
        /// </summary>
        public static string HelpWindowParagraphOpenBrowser2 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphOpenBrowser2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program crashes..
        /// </summary>
        public static string HelpWindowParagraphProgramCrashes1 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphProgramCrashes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the program crashes,.
        /// </summary>
        public static string HelpWindowParagraphProgramCrashes2 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphProgramCrashes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact me.
        /// </summary>
        public static string HelpWindowParagraphProgramCrashes3 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphProgramCrashes3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Try to describe clearly what happened. What channel are you listening to? It would be helpful to send me the error log as well..
        /// </summary>
        public static string HelpWindowParagraphProgramCrashes4 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphProgramCrashes4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to find the error log?.
        /// </summary>
        public static string HelpWindowParagraphProgramCrashes5 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphProgramCrashes5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why others can not hear the music what I share from the shared URL?.
        /// </summary>
        public static string HelpWindowParagraphShareParagraph1 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphShareParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Douban only allows some websites linked to douban.fm. i.e. Click shared URL from renren.com will be redirected to homepage of douban.fm. You can copy the URL, then paste it to the address bar of browser..
        /// </summary>
        public static string HelpWindowParagraphShareParagraph2 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphShareParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Documentation of DoubanFM.
        /// </summary>
        public static string HelpWindowParagraphTitle {
            get {
                return ResourceManager.GetString("HelpWindowParagraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpWindowTitle {
            get {
                return ResourceManager.GetString("HelpWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide lyrics.
        /// </summary>
        public static string HideLyrics {
            get {
                return ResourceManager.GetString("HideLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string HostComputerLabel {
            get {
                return ResourceManager.GetString("HostComputerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Key Settings.
        /// </summary>
        public static string HotKeySettingsButton {
            get {
                return ResourceManager.GetString("HotKeySettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never play.
        /// </summary>
        public static string HotKeySettingWindowDontPlayHotkeyTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowDontPlayHotkeyTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string HotKeySettingWindowLikeHotkeyTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowLikeHotkeyTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multimedia keys &apos;Play/Pause&apos; and &apos;Next&apos; are set..
        /// </summary>
        public static string HotKeySettingWindowMediaKeyInfoTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowMediaKeyInfoTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute/Unmute.
        /// </summary>
        public static string HotKeySettingWindowMuteSwitchTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowMuteSwitchTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next track.
        /// </summary>
        public static string HotKeySettingWindowNextHotkeyTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowNextHotkeyTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/Pause.
        /// </summary>
        public static string HotKeySettingWindowPlayPauseHotkeyTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowPlayPauseHotkeyTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search download.
        /// </summary>
        public static string HotKeySettingWindowSearchDownloadTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowSearchDownloadTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-key share.
        /// </summary>
        public static string HotKeySettingWindowShareKeyTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowShareKeyTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide lyrics.
        /// </summary>
        public static string HotKeySettingWindowShowHideLyricsTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowShowHideLyricsTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide window.
        /// </summary>
        public static string HotKeySettingWindowShowHideTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowShowHideTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Minimize window.
        /// </summary>
        public static string HotKeySettingWindowShowMinimizeTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowShowMinimizeTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume down.
        /// </summary>
        public static string HotKeySettingWindowVolumeDecreaseTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowVolumeDecreaseTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume up.
        /// </summary>
        public static string HotKeySettingWindowVolumeIncreaseTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowVolumeIncreaseTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ImportButton {
            get {
                return ResourceManager.GetString("ImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string InfoTab {
            get {
                return ResourceManager.GetString("InfoTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Settings.
        /// </summary>
        public static string InterfaceSettingsButton {
            get {
                return ResourceManager.GetString("InterfaceSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language setting is changed. It will take effect the next time you start DoubanFM..
        /// </summary>
        public static string LanguageChangedHint {
            get {
                return ResourceManager.GetString("LanguageChangedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageTextBlock {
            get {
                return ResourceManager.GetString("LanguageTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string LeftAlignment {
            get {
                return ResourceManager.GetString("LeftAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string LikeThumbButton {
            get {
                return ResourceManager.GetString("LikeThumbButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen.
        /// </summary>
        public static string Listen {
            get {
                return ResourceManager.GetString("Listen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging In.
        /// </summary>
        public static string LoggingInLabel {
            get {
                return ResourceManager.GetString("LoggingInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Out.
        /// </summary>
        public static string LoggingOutLabel {
            get {
                return ResourceManager.GetString("LoggingOutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics Settings.
        /// </summary>
        public static string LyricsSettingsButton {
            get {
                return ResourceManager.GetString("LyricsSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string LyricsSettingsWindowColorGB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowColorGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Lyrics Settings.
        /// </summary>
        public static string LyricsSettingsWindowDesktopLyricsGroupBox {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowDesktopLyricsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two lines.
        /// </summary>
        public static string LyricsSettingsWindowDoubleLineLyricsRadioButton {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowDoubleLineLyricsRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        public static string LyricsSettingsWindowForegroundColorTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowForegroundColorTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide when music is paused.
        /// </summary>
        public static string LyricsSettingsWindowHideWhenPauseCb {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowHideWhenPauseCb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H. Alignment.
        /// </summary>
        public static string LyricsSettingsWindowHorizontalAlignmentTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowHorizontalAlignmentTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string LyricsSettingsWindowLayoutGB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowLayoutGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B. Margin.
        /// </summary>
        public static string LyricsSettingsWindowMarginBottomTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowMarginBottomTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L. Margin.
        /// </summary>
        public static string LyricsSettingsWindowMarginLeftTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowMarginLeftTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R. Margin.
        /// </summary>
        public static string LyricsSettingsWindowMarginRightTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowMarginRightTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T. Margin.
        /// </summary>
        public static string LyricsSettingsWindowMarginTopTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowMarginTopTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU usage may rise.
        /// </summary>
        public static string LyricsSettingsWindowOccupyCPULabel {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowOccupyCPULabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output device.
        /// </summary>
        public static string LyricsSettingsWindowOutputDisplayTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowOutputDisplayTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow.
        /// </summary>
        public static string LyricsSettingsWindowShadowColorTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowShadowColorTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single line.
        /// </summary>
        public static string LyricsSettingsWindowSingleLineLyricsRadioButton {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowSingleLineLyricsRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string LyricsSettingsWindowSizeTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowSizeTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stroke.
        /// </summary>
        public static string LyricsSettingsWindowStrokeColorTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowStrokeColorTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stroke weight.
        /// </summary>
        public static string LyricsSettingsWindowStrokeWeightTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowStrokeWeightTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string LyricsSettingsWindowThicknessTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowThicknessTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force on topmost.
        /// </summary>
        public static string LyricsSettingsWindowTopMostCb {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowTopMostCb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force on topmost can effectively solve the problem of lyrics not displaying over applications. But it may display over some full screen applications as well..
        /// </summary>
        public static string LyricsSettingsWindowTopMostCbToolTip {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowTopMostCbToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency.
        /// </summary>
        public static string LyricsSettingsWindowTransparencyTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowTransparencyTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typeface.
        /// </summary>
        public static string LyricsSettingsWindowTypefaceTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowTypefaceTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V. Alignment.
        /// </summary>
        public static string LyricsSettingsWindowVerticalAlignmentTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowVerticalAlignmentTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string LyricsSettingsWindowWritingGB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowWritingGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        public static string LyricsWindowLyricsRoot1TB {
            get {
                return ResourceManager.GetString("LyricsWindowLyricsRoot1TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to next page to see more results..
        /// </summary>
        public static string MayNextResultsLabel {
            get {
                return ResourceManager.GetString("MayNextResultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray icon.
        /// </summary>
        public static string MinimizeToTray {
            get {
                return ResourceManager.GetString("MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextThumbButton {
            get {
                return ResourceManager.GetString("NextThumbButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned: {0}.
        /// </summary>
        public static string NoLongerPlayFormatString {
            get {
                return ResourceManager.GetString("NoLongerPlayFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output device.
        /// </summary>
        public static string OutputDevicesTextBlock {
            get {
                return ResourceManager.GetString("OutputDevicesTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor: {0}.
        /// </summary>
        public static string OutputScreenFormatString {
            get {
                return ResourceManager.GetString("OutputScreenFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordBlock {
            get {
                return ResourceManager.GetString("PasswordBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string PauseThumbButton {
            get {
                return ResourceManager.GetString("PauseThumbButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string PersonalRadioRB {
            get {
                return ResourceManager.GetString("PersonalRadioRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string PlayThumbButton {
            get {
                return ResourceManager.GetString("PlayThumbButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        public static string PleaseWaitLabel {
            get {
                return ResourceManager.GetString("PleaseWaitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like: {0}.
        /// </summary>
        public static string PlusHeartsFormatString {
            get {
                return ResourceManager.GetString("PlusHeartsFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string PortLabel {
            get {
                return ResourceManager.GetString("PortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave username/password blank if not required..
        /// </summary>
        public static string ProxyNoCredentialsLabel {
            get {
                return ResourceManager.GetString("ProxyNoCredentialsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        public static string ProxyServerGroupBox {
            get {
                return ResourceManager.GetString("ProxyServerGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string PublicRadioRB {
            get {
                return ResourceManager.GetString("PublicRadioRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide cover when clicked..
        /// </summary>
        public static string RadioButtonSlideCoverWhenClick {
            get {
                return ResourceManager.GetString("RadioButtonSlideCoverWhenClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide cover when the mouse hovers over..
        /// </summary>
        public static string RadioButtonSlideCoverWhenMouseMove {
            get {
                return ResourceManager.GetString("RadioButtonSlideCoverWhenMouseMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string RbCustomProxy {
            get {
                return ResourceManager.GetString("RbCustomProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string RbDefaultProxy {
            get {
                return ResourceManager.GetString("RbDefaultProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string RbNoProxy {
            get {
                return ResourceManager.GetString("RbNoProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to refresh captcha..
        /// </summary>
        public static string RefreshVerificationCaptchaButton {
            get {
                return ResourceManager.GetString("RefreshVerificationCaptchaButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMeCheckBox {
            get {
                return ResourceManager.GetString("RememberMeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetButton {
            get {
                return ResourceManager.GetString("ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reset settings.
        /// </summary>
        public static string ResetFailed {
            get {
                return ResourceManager.GetString("ResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to reset settings?
        ///Application will restart after reset..
        /// </summary>
        public static string ResetWarning {
            get {
                return ResourceManager.GetString("ResetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string RightAlignment {
            get {
                return ResourceManager.GetString("RightAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string SearchingLabel {
            get {
                return ResourceManager.GetString("SearchingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Remove search results that can not be played&quot; is checked..
        /// </summary>
        public static string SearchResultsCanNotListenLabel {
            get {
                return ResourceManager.GetString("SearchResultsCanNotListenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchTab {
            get {
                return ResourceManager.GetString("SearchTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send error report.
        /// </summary>
        public static string SendErrorButton {
            get {
                return ResourceManager.GetString("SendErrorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set proxy failed.
        /// </summary>
        public static string SetProxyFailed {
            get {
                return ResourceManager.GetString("SetProxyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTab {
            get {
                return ResourceManager.GetString("SettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Douban.
        /// </summary>
        public static string ShareDouban {
            get {
                return ResourceManager.GetString("ShareDouban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Facebook.
        /// </summary>
        public static string ShareFacebook {
            get {
                return ResourceManager.GetString("ShareFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Fanfou.
        /// </summary>
        public static string ShareFanfou {
            get {
                return ResourceManager.GetString("ShareFanfou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Kaixin.
        /// </summary>
        public static string ShareKaixin {
            get {
                return ResourceManager.GetString("ShareKaixin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-key share.
        /// </summary>
        public static string ShareKeyButton {
            get {
                return ResourceManager.GetString("ShareKeyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on MSN.
        /// </summary>
        public static string ShareMsn {
            get {
                return ResourceManager.GetString("ShareMsn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Qzone.
        /// </summary>
        public static string ShareQzone {
            get {
                return ResourceManager.GetString("ShareQzone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Renren.
        /// </summary>
        public static string ShareRenren {
            get {
                return ResourceManager.GetString("ShareRenren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Settings.
        /// </summary>
        public static string ShareSettingsButton {
            get {
                return ResourceManager.GetString("ShareSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable one-key share.
        /// </summary>
        public static string ShareSettingsWindowEnableKeyShareCb {
            get {
                return ResourceManager.GetString("ShareSettingsWindowEnableKeyShareCb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites to share on when use one-key share:.
        /// </summary>
        public static string ShareSettingsWindowKeyShareSiteLabel {
            get {
                return ResourceManager.GetString("ShareSettingsWindowKeyShareSiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share buttons to display:.
        /// </summary>
        public static string ShareSettingsWindowShareButtonLabel {
            get {
                return ResourceManager.GetString("ShareSettingsWindowShareButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Douban.
        /// </summary>
        public static string ShareSiteDouban {
            get {
                return ResourceManager.GetString("ShareSiteDouban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string ShareSiteFacebook {
            get {
                return ResourceManager.GetString("ShareSiteFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fanfou.
        /// </summary>
        public static string ShareSiteFanfou {
            get {
                return ResourceManager.GetString("ShareSiteFanfou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaixin.
        /// </summary>
        public static string ShareSiteKaixin {
            get {
                return ResourceManager.GetString("ShareSiteKaixin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSN.
        /// </summary>
        public static string ShareSiteMsn {
            get {
                return ResourceManager.GetString("ShareSiteMsn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Copy to clipboard*.
        /// </summary>
        public static string ShareSiteNone {
            get {
                return ResourceManager.GetString("ShareSiteNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qzone.
        /// </summary>
        public static string ShareSiteQzone {
            get {
                return ResourceManager.GetString("ShareSiteQzone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renren.
        /// </summary>
        public static string ShareSiteRenren {
            get {
                return ResourceManager.GetString("ShareSiteRenren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tencent Weibo.
        /// </summary>
        public static string ShareSiteTencentWeibo {
            get {
                return ResourceManager.GetString("ShareSiteTencentWeibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string ShareSiteTwitter {
            get {
                return ResourceManager.GetString("ShareSiteTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sina Weibo.
        /// </summary>
        public static string ShareSiteWeibo {
            get {
                return ResourceManager.GetString("ShareSiteWeibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Tencent Weibo.
        /// </summary>
        public static string ShareTencentWeibo {
            get {
                return ResourceManager.GetString("ShareTencentWeibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m listening to {1} - {0}.
        /// </summary>
        public static string ShareText1 {
            get {
                return ResourceManager.GetString("ShareText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Twitter.
        /// </summary>
        public static string ShareTwitter {
            get {
                return ResourceManager.GetString("ShareTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Sina Weibo.
        /// </summary>
        public static string ShareWeibo {
            get {
                return ResourceManager.GetString("ShareWeibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error summary:.
        /// </summary>
        public static string ShortMessageTextBlock {
            get {
                return ResourceManager.GetString("ShortMessageTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Lyrics.
        /// </summary>
        public static string ShowLyrics {
            get {
                return ResourceManager.GetString("ShowLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string SoftwareHome {
            get {
                return ResourceManager.GetString("SoftwareHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify.
        /// </summary>
        public static string StretchAlignment {
            get {
                return ResourceManager.GetString("StretchAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully copied.
        /// </summary>
        public static string SuccessfullyCopied {
            get {
                return ResourceManager.GetString("SuccessfullyCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in.
        /// </summary>
        public static string TheLoggedLabel {
            get {
                return ResourceManager.GetString("TheLoggedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A third-party client.
        /// </summary>
        public static string ThirdPartyClientsBlock {
            get {
                return ResourceManager.GetString("ThirdPartyClientsBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string TopAlignment {
            get {
                return ResourceManager.GetString("TopAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0}.
        /// </summary>
        public static string TotalFormatString {
            get {
                return ResourceManager.GetString("TotalFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto remove brackets and their contents..
        /// </summary>
        public static string TrimBracketsCheckBox {
            get {
                return ResourceManager.GetString("TrimBracketsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main UI font.
        /// </summary>
        public static string UISettingsWindowMainInterfaceFontTextBlock {
            get {
                return ResourceManager.GetString("UISettingsWindowMainInterfaceFontTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main UI scale.
        /// </summary>
        public static string UISettingsWindowMainInterfaceScaleTextBlock {
            get {
                return ResourceManager.GetString("UISettingsWindowMainInterfaceScaleTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup a balloon when playing song is changed..
        /// </summary>
        public static string UISettingsWindowPopupCb {
            get {
                return ResourceManager.GetString("UISettingsWindowPopupCb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window background.
        /// </summary>
        public static string UISettingsWindowWindowBackgroundGB {
            get {
                return ResourceManager.GetString("UISettingsWindowWindowBackgroundGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually specify the color..
        /// </summary>
        public static string UISettingsWindowWindowManualColorCB {
            get {
                return ResourceManager.GetString("UISettingsWindowWindowManualColorCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum.
        /// </summary>
        public static string UISettingsWindowWindowSpectrumCB {
            get {
                return ResourceManager.GetString("UISettingsWindowWindowSpectrumCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from favorites.
        /// </summary>
        public static string UnfavoriteButton {
            get {
                return ResourceManager.GetString("UnfavoriteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlike.
        /// </summary>
        public static string UnlikeThumbButton {
            get {
                return ResourceManager.GetString("UnlikeThumbButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyed URL to clipboard.
        /// </summary>
        public static string UrlCopyedToClipboard {
            get {
                return ResourceManager.GetString("UrlCopyedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please explain what you were doing, to help with analyzing the problem..
        /// </summary>
        public static string UserMessageTextBlock {
            get {
                return ResourceManager.GetString("UserMessageTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserNameLabel {
            get {
                return ResourceManager.GetString("UserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha.
        /// </summary>
        public static string VerificationCaptchaBlock {
            get {
                return ResourceManager.GetString("VerificationCaptchaBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the error report..
        /// </summary>
        public static string ViewErrorMessageButton {
            get {
                return ResourceManager.GetString("ViewErrorMessageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoubanFM.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoubanFM.
        /// </summary>
        public static string WindowTitleShort {
            get {
                return ResourceManager.GetString("WindowTitleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip files.
        /// </summary>
        public static string ZipFileFilterName {
            get {
                return ResourceManager.GetString("ZipFileFilterName", resourceCulture);
            }
        }
    }
}
