//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.32559
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoubanFM.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoubanFM.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Account 的本地化字符串。
        /// </summary>
        public static string AccountTab {
            get {
                return ResourceManager.GetString("AccountTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        public static string AlbumInfoPage {
            get {
                return ResourceManager.GetString("AlbumInfoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include album title 的本地化字符串。
        /// </summary>
        public static string AlbumSearchCheckBox {
            get {
                return ResourceManager.GetString("AlbumSearchCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application will be shut down 的本地化字符串。
        /// </summary>
        public static string ApplicationWillClose {
            get {
                return ResourceManager.GetString("ApplicationWillClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Artist 的本地化字符串。
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto login 的本地化字符串。
        /// </summary>
        public static string AutoLoginCheckBox {
            get {
                return ResourceManager.GetString("AutoLoginCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available after login 的本地化字符串。
        /// </summary>
        public static string AvailableAfterLoginBorder {
            get {
                return ResourceManager.GetString("AvailableAfterLoginBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bit rate 的本地化字符串。
        /// </summary>
        public static string BitRate {
            get {
                return ResourceManager.GetString("BitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom 的本地化字符串。
        /// </summary>
        public static string BottomAlignment {
            get {
                return ResourceManager.GetString("BottomAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        public static string BtnApplyProxy {
            get {
                return ResourceManager.GetString("BtnApplyProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string BtnScaleTransformReset {
            get {
                return ResourceManager.GetString("BtnScaleTransformReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        public static string CbAutoForeground {
            get {
                return ResourceManager.GetString("CbAutoForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desktop lyrics 的本地化字符串。
        /// </summary>
        public static string CbEnableDesktopLyrics {
            get {
                return ResourceManager.GetString("CbEnableDesktopLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Embedded lyrics 的本地化字符串。
        /// </summary>
        public static string CbEnableEmbeddedLyrics {
            get {
                return ResourceManager.GetString("CbEnableEmbeddedLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Baidu Music 的本地化字符串。
        /// </summary>
        public static string CbSearchBaiduMusic {
            get {
                return ResourceManager.GetString("CbSearchBaiduMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search QQ Music 的本地化字符串。
        /// </summary>
        public static string CbSearchQQMusic {
            get {
                return ResourceManager.GetString("CbSearchQQMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable lyrics 的本地化字符串。
        /// </summary>
        public static string CbShowLyrics {
            get {
                return ResourceManager.GetString("CbShowLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show lyrics borders to help adjust layout 的本地化字符串。
        /// </summary>
        public static string CbShowLyricsBackground {
            get {
                return ResourceManager.GetString("CbShowLyricsBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center 的本地化字符串。
        /// </summary>
        public static string CenterAlignment {
            get {
                return ResourceManager.GetString("CenterAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Channels 的本地化字符串。
        /// </summary>
        public static string ChannelsTab {
            get {
                return ResourceManager.GetString("ChannelsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adjust volume with mouse wheel 的本地化字符串。
        /// </summary>
        public static string CheckBoxAdjustVolumeWithMouseWheel {
            get {
                return ResourceManager.GetString("CheckBoxAdjustVolumeWithMouseWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always show tray icon 的本地化字符串。
        /// </summary>
        public static string CheckBoxAlwaysShowNotifyIcon {
            get {
                return ResourceManager.GetString("CheckBoxAlwaysShowNotifyIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Limit download speed 的本地化字符串。
        /// </summary>
        public static string CheckBoxEnableDownloadRateRestriction {
            get {
                return ResourceManager.GetString("CheckBoxEnableDownloadRateRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove search results that can not be played 的本地化字符串。
        /// </summary>
        public static string CheckBoxIsSearchFilterEnabled {
            get {
                return ResourceManager.GetString("CheckBoxIsSearchFilterEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open album info when cover is clicked 的本地化字符串。
        /// </summary>
        public static string CheckBoxOpenAlbumInfoWhenClickCover {
            get {
                return ResourceManager.GetString("CheckBoxOpenAlbumInfoWhenClickCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remember channel played last 的本地化字符串。
        /// </summary>
        public static string CheckBoxRememberLastChannel {
            get {
                return ResourceManager.GetString("CheckBoxRememberLastChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always on top 的本地化字符串。
        /// </summary>
        public static string CheckBoxTopMost {
            get {
                return ResourceManager.GetString("CheckBoxTopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for updates 的本地化字符串。
        /// </summary>
        public static string CheckforUpdates {
            get {
                return ResourceManager.GetString("CheckforUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search results from music.douban.com 的本地化字符串。
        /// </summary>
        public static string ConsistentResultsLabel {
            get {
                return ResourceManager.GetString("ConsistentResultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Share (click to copy link) 的本地化字符串。
        /// </summary>
        public static string CopyUrlButton {
            get {
                return ResourceManager.GetString("CopyUrlButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DJ 的本地化字符串。
        /// </summary>
        public static string DJRadioRB {
            get {
                return ResourceManager.GetString("DJRadioRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click &apos;Search&apos; for all channels 的本地化字符串。
        /// </summary>
        public static string DJSearchTextBlock {
            get {
                return ResourceManager.GetString("DJSearchTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate 的本地化字符串。
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Never play again 的本地化字符串。
        /// </summary>
        public static string DontPlayThumbButton {
            get {
                return ResourceManager.GetString("DontPlayThumbButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The DoubanFM official website 的本地化字符串。
        /// </summary>
        public static string DoubanFMOfficialWebsite {
            get {
                return ResourceManager.GetString("DoubanFMOfficialWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search for music downloads 的本地化字符串。
        /// </summary>
        public static string DownloadSearchButton {
            get {
                return ResourceManager.GetString("DownloadSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Searching Settings 的本地化字符串。
        /// </summary>
        public static string DownloadSearchSettingsGroupBox {
            get {
                return ResourceManager.GetString("DownloadSearchSettingsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username 的本地化字符串。
        /// </summary>
        public static string EmailUserNameBlock {
            get {
                return ResourceManager.GetString("EmailUserNameBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error has occured 的本地化字符串。
        /// </summary>
        public static string ExceptionWindowTitle {
            get {
                return ResourceManager.GetString("ExceptionWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add to favorites 的本地化字符串。
        /// </summary>
        public static string FavoriteButton {
            get {
                return ResourceManager.GetString("FavoriteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feedback 的本地化字符串。
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move the mouse to the cover
        ///Surprise! 的本地化字符串。
        /// </summary>
        public static string FirstTimePanelTextBlock {
            get {
                return ResourceManager.GetString("FirstTimePanelTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General Settings 的本地化字符串。
        /// </summary>
        public static string GeneralSettingsButton {
            get {
                return ResourceManager.GetString("GeneralSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Obtaining play list failed : {0} 的本地化字符串。
        /// </summary>
        public static string GetPlayListFailedMessage {
            get {
                return ResourceManager.GetString("GetPlayListFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disclaimer: This software is a third-party client, not official. 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphDisclaimer1 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphDisclaimer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author: 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphDisclaimer2 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphDisclaimer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Homepage: 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphDisclaimer3 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphDisclaimer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Web version FAQ: 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphDisclaimer4 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphDisclaimer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DoubanFM official website: 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphDisclaimer5 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphDisclaimer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The DoubanFM Help and Support: 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphDisclaimer6 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphDisclaimer6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 What to do with unclear texts after font changes? 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphFontModification1 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontModification1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can zoom in main window so that the words are easier to be read. 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphFontModification2 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontModification2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Why I can&apos;t use the software once logged in until I reset all the settings? 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphFontModification3 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontModification3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 How to set a font? 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphFontSet {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When you set the fonts, you can use the font name in multiple languages. All fonts have English names and non-English fonts, for the most of times, have non-English names. For example, 宋体 has a English name &quot;SimSun&quot;, while 新宋体 has the English name &quot;NSimsun&quot;. 楷体 has its English name as &quot;KaiTi&quot;; the English name of 微软雅黑 is Microsoft YaHei. In Taiwan, the default Windows 7 Chinese font is 微軟正黑體, whose English name is Microsoft Jhenghei. In this application, only fonts that have Simplified Chinese names are sho [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphFontSet10 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontSet10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can set multiple fonts in this application. When you use some Chinese fonts, you will find their Latin glyphs don&apos;t look so nice. So it is necessary to specify fonts for Chinese and English respectively. Here&apos;s an example: 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphFontSet2 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontSet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 豆瓣电台 豆瓣電台 DoubanFM 1234567 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphFontSet3 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontSet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple fonts can be designated here with descending priority and separated by commas (either half-width or full-width will do). If some certain text can not be displayed in any designated fonts, the system default font will be used. Usually the English font is put before the Chinese one. The font should be set by inputing the name of the font like &quot;Century,华文新魏&quot;, rather than selecting from the drop-down list. An English font that is designated after the Chinese font will often fail to apply because Chines [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphFontSet4 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontSet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The font not found in the system will be ignored. Other fonts will function as normal. 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphFontSet5 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontSet5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From the example above, we can see that 华文新魏 does not include Traditional Chinese characters, so those ones will be shown in default font. Here we can set a third font: 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphFontSet6 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontSet6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Case-insensitive: 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphFontSet7 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontSet7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spaces are allowed before and after a font. 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphFontSet8 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontSet8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light, SemiLight, SemiBold and Bold can also be added after the font to specify a weight. So that adjusting weight in lyrics settings will not affect the font itself. (Some fonts might not have a variety of weights. Usually there are only two weights for Chinese fonts. English fonts have more. A good example is that Segoe UI supports Light, SemiBold and Bold, but not SemiLight.) 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphFontSet9 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphFontSet9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I logged in and checked &quot;Auto Log in&quot;. Why auto log in doesn&apos;t function when I open the application next time? 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphLogin1 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphLogin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Usually it&apos;s because you log out in a browser. Once you log out from one place, all other pages will be logged out too, including this application. That is to say, if you log in Douban in multiple browsers and log out in one of them, you will find your douban account is logged out in all broswers. So the only solution to this problem is to avoid logging out at other pages. 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphLogin2 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphLogin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphOpenBrowser1 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphOpenBrowser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 and login. Please check if you account has abnormal usage records. It might be that your account is locked or yet to be actived. 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphOpenBrowser2 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphOpenBrowser2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The program crashed. 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphProgramCrashes1 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphProgramCrashes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If the program crashes, 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphProgramCrashes2 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphProgramCrashes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 contact me 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphProgramCrashes3 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphProgramCrashes3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 . Please try to explain as detailed as possible what you were doing, or what channel you were listening to. Reports with error log are preferred. 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphProgramCrashes4 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphProgramCrashes4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Where to find the error log? 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphProgramCrashes5 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphProgramCrashes5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Why others can not listen to the music that I share by link? 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphShareParagraph1 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphShareParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Douban disallows some users to jump from certain websites. For example, when you click the link from RenRen.com, it would direct you to the front page of Douban.fm, which is effectively the same as visiting douban.fm in the broswer. You can copy the shared link and paste it into the address bar of the browser, then you can listen to the music. 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphShareParagraph2 {
            get {
                return ResourceManager.GetString("HelpWindowParagraphShareParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help Documentation of DoubanFM 的本地化字符串。
        /// </summary>
        public static string HelpWindowParagraphTitle {
            get {
                return ResourceManager.GetString("HelpWindowParagraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string HelpWindowTitle {
            get {
                return ResourceManager.GetString("HelpWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide lyrics 的本地化字符串。
        /// </summary>
        public static string HideLyrics {
            get {
                return ResourceManager.GetString("HideLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host 的本地化字符串。
        /// </summary>
        public static string HostComputerLabel {
            get {
                return ResourceManager.GetString("HostComputerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hot Key Settings 的本地化字符串。
        /// </summary>
        public static string HotKeySettingsButton {
            get {
                return ResourceManager.GetString("HotKeySettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Never play again 的本地化字符串。
        /// </summary>
        public static string HotKeySettingWindowDontPlayHotkeyTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowDontPlayHotkeyTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Like 的本地化字符串。
        /// </summary>
        public static string HotKeySettingWindowLikeHotkeyTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowLikeHotkeyTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multimedia keys &apos;Play/Pause&apos; and &apos;Next&apos; are set. 的本地化字符串。
        /// </summary>
        public static string HotKeySettingWindowMediaKeyInfoTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowMediaKeyInfoTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mute/Unmute 的本地化字符串。
        /// </summary>
        public static string HotKeySettingWindowMuteSwitchTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowMuteSwitchTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next track 的本地化字符串。
        /// </summary>
        public static string HotKeySettingWindowNextHotkeyTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowNextHotkeyTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play/Pause 的本地化字符串。
        /// </summary>
        public static string HotKeySettingWindowPlayPauseHotkeyTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowPlayPauseHotkeyTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search download 的本地化字符串。
        /// </summary>
        public static string HotKeySettingWindowSearchDownloadTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowSearchDownloadTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One-key share 的本地化字符串。
        /// </summary>
        public static string HotKeySettingWindowShareKeyTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowShareKeyTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide lyrics 的本地化字符串。
        /// </summary>
        public static string HotKeySettingWindowShowHideLyricsTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowShowHideLyricsTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide window 的本地化字符串。
        /// </summary>
        public static string HotKeySettingWindowShowHideTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowShowHideTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Minimize window 的本地化字符串。
        /// </summary>
        public static string HotKeySettingWindowShowMinimizeTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowShowMinimizeTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume down 的本地化字符串。
        /// </summary>
        public static string HotKeySettingWindowVolumeDecreaseTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowVolumeDecreaseTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume up 的本地化字符串。
        /// </summary>
        public static string HotKeySettingWindowVolumeIncreaseTextBlock {
            get {
                return ResourceManager.GetString("HotKeySettingWindowVolumeIncreaseTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string ImportButton {
            get {
                return ResourceManager.GetString("ImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        public static string InfoTab {
            get {
                return ResourceManager.GetString("InfoTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI Settings 的本地化字符串。
        /// </summary>
        public static string InterfaceSettingsButton {
            get {
                return ResourceManager.GetString("InterfaceSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language setting changed and will take effect at the next start up. 的本地化字符串。
        /// </summary>
        public static string LanguageChangedHint {
            get {
                return ResourceManager.GetString("LanguageChangedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string LanguageTextBlock {
            get {
                return ResourceManager.GetString("LanguageTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left 的本地化字符串。
        /// </summary>
        public static string LeftAlignment {
            get {
                return ResourceManager.GetString("LeftAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Like 的本地化字符串。
        /// </summary>
        public static string LikeThumbButton {
            get {
                return ResourceManager.GetString("LikeThumbButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Listen 的本地化字符串。
        /// </summary>
        public static string Listen {
            get {
                return ResourceManager.GetString("Listen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logging In 的本地化字符串。
        /// </summary>
        public static string LoggingInLabel {
            get {
                return ResourceManager.GetString("LoggingInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logging Out 的本地化字符串。
        /// </summary>
        public static string LoggingOutLabel {
            get {
                return ResourceManager.GetString("LoggingOutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 的本地化字符串。
        /// </summary>
        public static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lyrics Settings 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsButton {
            get {
                return ResourceManager.GetString("LyricsSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Colors 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowColorGB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowColorGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desktop Lyrics Settings 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowDesktopLyricsGroupBox {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowDesktopLyricsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double lines 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowDoubleLineLyricsRadioButton {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowDoubleLineLyricsRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Foreground 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowForegroundColorTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowForegroundColorTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide when music is paused 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowHideWhenPauseCb {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowHideWhenPauseCb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 H. Alignment 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowHorizontalAlignmentTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowHorizontalAlignmentTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layout 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowLayoutGB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowLayoutGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B. Margin 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowMarginBottomTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowMarginBottomTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L. Margin 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowMarginLeftTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowMarginLeftTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R. Margin 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowMarginRightTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowMarginRightTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 T. Margin 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowMarginTopTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowMarginTopTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU usage may rise 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowOccupyCPULabel {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowOccupyCPULabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output device 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowOutputDisplayTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowOutputDisplayTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shadow 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowShadowColorTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowShadowColorTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single line 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowSingleLineLyricsRadioButton {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowSingleLineLyricsRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowSizeTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowSizeTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stroke 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowStrokeColorTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowStrokeColorTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stroke weight 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowStrokeWeightTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowStrokeWeightTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weight 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowThicknessTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowThicknessTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force on top 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowTopMostCb {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowTopMostCb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force on top can do the magic when you got the problem that lyrics are not shown on top. However, it may still show when running some fullscreen programs. 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowTopMostCbToolTip {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowTopMostCbToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transparency 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowTransparencyTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowTransparencyTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowTypefaceTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowTypefaceTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V. Alignment 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowVerticalAlignmentTB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowVerticalAlignmentTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font 的本地化字符串。
        /// </summary>
        public static string LyricsSettingsWindowWritingGB {
            get {
                return ResourceManager.GetString("LyricsSettingsWindowWritingGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Placeholder 的本地化字符串。
        /// </summary>
        public static string LyricsWindowLyricsRoot1TB {
            get {
                return ResourceManager.GetString("LyricsWindowLyricsRoot1TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check out the next page 的本地化字符串。
        /// </summary>
        public static string MayNextResultsLabel {
            get {
                return ResourceManager.GetString("MayNextResultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize 的本地化字符串。
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize to tray icon 的本地化字符串。
        /// </summary>
        public static string MinimizeToTray {
            get {
                return ResourceManager.GetString("MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Page 的本地化字符串。
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        public static string NextThumbButton {
            get {
                return ResourceManager.GetString("NextThumbButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disliked: {0} 的本地化字符串。
        /// </summary>
        public static string NoLongerPlayFormatString {
            get {
                return ResourceManager.GetString("NoLongerPlayFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output device 的本地化字符串。
        /// </summary>
        public static string OutputDevicesTextBlock {
            get {
                return ResourceManager.GetString("OutputDevicesTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor: {0} 的本地化字符串。
        /// </summary>
        public static string OutputScreenFormatString {
            get {
                return ResourceManager.GetString("OutputScreenFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string PasswordBlock {
            get {
                return ResourceManager.GetString("PasswordBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause 的本地化字符串。
        /// </summary>
        public static string PauseThumbButton {
            get {
                return ResourceManager.GetString("PauseThumbButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Personal 的本地化字符串。
        /// </summary>
        public static string PersonalRadioRB {
            get {
                return ResourceManager.GetString("PersonalRadioRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play 的本地化字符串。
        /// </summary>
        public static string PlayThumbButton {
            get {
                return ResourceManager.GetString("PlayThumbButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Wait 的本地化字符串。
        /// </summary>
        public static string PleaseWaitLabel {
            get {
                return ResourceManager.GetString("PleaseWaitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Liked: {0} 的本地化字符串。
        /// </summary>
        public static string PlusHeartsFormatString {
            get {
                return ResourceManager.GetString("PlusHeartsFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        public static string PortLabel {
            get {
                return ResourceManager.GetString("PortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous Page 的本地化字符串。
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Leave username/password blank if not required. 的本地化字符串。
        /// </summary>
        public static string ProxyNoCredentialsLabel {
            get {
                return ResourceManager.GetString("ProxyNoCredentialsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy 的本地化字符串。
        /// </summary>
        public static string ProxyServerGroupBox {
            get {
                return ResourceManager.GetString("ProxyServerGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Public 的本地化字符串。
        /// </summary>
        public static string PublicRadioRB {
            get {
                return ResourceManager.GetString("PublicRadioRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slide cover when clicked 的本地化字符串。
        /// </summary>
        public static string RadioButtonSlideCoverWhenClick {
            get {
                return ResourceManager.GetString("RadioButtonSlideCoverWhenClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slide cover when the mouse hovers over 的本地化字符串。
        /// </summary>
        public static string RadioButtonSlideCoverWhenMouseMove {
            get {
                return ResourceManager.GetString("RadioButtonSlideCoverWhenMouseMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        public static string RbCustomProxy {
            get {
                return ResourceManager.GetString("RbCustomProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string RbDefaultProxy {
            get {
                return ResourceManager.GetString("RbDefaultProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string RbNoProxy {
            get {
                return ResourceManager.GetString("RbNoProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to refresh captcha. 的本地化字符串。
        /// </summary>
        public static string RefreshVerificationCaptchaButton {
            get {
                return ResourceManager.GetString("RefreshVerificationCaptchaButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register 的本地化字符串。
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remember password 的本地化字符串。
        /// </summary>
        public static string RememberPasswordCheckBox {
            get {
                return ResourceManager.GetString("RememberPasswordCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string ResetButton {
            get {
                return ResourceManager.GetString("ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset failed 的本地化字符串。
        /// </summary>
        public static string ResetFailed {
            get {
                return ResourceManager.GetString("ResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to reset settings?
        ///Application will restart after reset. 的本地化字符串。
        /// </summary>
        public static string ResetWarning {
            get {
                return ResourceManager.GetString("ResetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retry 的本地化字符串。
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right 的本地化字符串。
        /// </summary>
        public static string RightAlignment {
            get {
                return ResourceManager.GetString("RightAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Searching... 的本地化字符串。
        /// </summary>
        public static string SearchingLabel {
            get {
                return ResourceManager.GetString("SearchingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;Remove search results that can not be played&quot; is checked. 的本地化字符串。
        /// </summary>
        public static string SearchResultsCanNotListenLabel {
            get {
                return ResourceManager.GetString("SearchResultsCanNotListenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string SearchTab {
            get {
                return ResourceManager.GetString("SearchTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send error report 的本地化字符串。
        /// </summary>
        public static string SendErrorButton {
            get {
                return ResourceManager.GetString("SendErrorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set proxy failed 的本地化字符串。
        /// </summary>
        public static string SetProxyFailed {
            get {
                return ResourceManager.GetString("SetProxyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string SettingsTab {
            get {
                return ResourceManager.GetString("SettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Share on Douban 的本地化字符串。
        /// </summary>
        public static string ShareDouban {
            get {
                return ResourceManager.GetString("ShareDouban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Share on Facebook 的本地化字符串。
        /// </summary>
        public static string ShareFacebook {
            get {
                return ResourceManager.GetString("ShareFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Share on Fanfou 的本地化字符串。
        /// </summary>
        public static string ShareFanfou {
            get {
                return ResourceManager.GetString("ShareFanfou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Share on Kaixin 的本地化字符串。
        /// </summary>
        public static string ShareKaixin {
            get {
                return ResourceManager.GetString("ShareKaixin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One-key share 的本地化字符串。
        /// </summary>
        public static string ShareKeyButton {
            get {
                return ResourceManager.GetString("ShareKeyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Share on MSN 的本地化字符串。
        /// </summary>
        public static string ShareMsn {
            get {
                return ResourceManager.GetString("ShareMsn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Share on Qzone 的本地化字符串。
        /// </summary>
        public static string ShareQzone {
            get {
                return ResourceManager.GetString("ShareQzone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Share on Renren 的本地化字符串。
        /// </summary>
        public static string ShareRenren {
            get {
                return ResourceManager.GetString("ShareRenren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Share Settings 的本地化字符串。
        /// </summary>
        public static string ShareSettingsButton {
            get {
                return ResourceManager.GetString("ShareSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable one-key share 的本地化字符串。
        /// </summary>
        public static string ShareSettingsWindowEnableKeyShareCb {
            get {
                return ResourceManager.GetString("ShareSettingsWindowEnableKeyShareCb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sites to share on when use one-key share: 的本地化字符串。
        /// </summary>
        public static string ShareSettingsWindowKeyShareSiteLabel {
            get {
                return ResourceManager.GetString("ShareSettingsWindowKeyShareSiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Share buttons to show: 的本地化字符串。
        /// </summary>
        public static string ShareSettingsWindowShareButtonLabel {
            get {
                return ResourceManager.GetString("ShareSettingsWindowShareButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Douban 的本地化字符串。
        /// </summary>
        public static string ShareSiteDouban {
            get {
                return ResourceManager.GetString("ShareSiteDouban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Facebook 的本地化字符串。
        /// </summary>
        public static string ShareSiteFacebook {
            get {
                return ResourceManager.GetString("ShareSiteFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fanfou 的本地化字符串。
        /// </summary>
        public static string ShareSiteFanfou {
            get {
                return ResourceManager.GetString("ShareSiteFanfou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kaixin 的本地化字符串。
        /// </summary>
        public static string ShareSiteKaixin {
            get {
                return ResourceManager.GetString("ShareSiteKaixin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MSN 的本地化字符串。
        /// </summary>
        public static string ShareSiteMsn {
            get {
                return ResourceManager.GetString("ShareSiteMsn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *Copy to clipboard* 的本地化字符串。
        /// </summary>
        public static string ShareSiteNone {
            get {
                return ResourceManager.GetString("ShareSiteNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Qzone 的本地化字符串。
        /// </summary>
        public static string ShareSiteQzone {
            get {
                return ResourceManager.GetString("ShareSiteQzone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Renren 的本地化字符串。
        /// </summary>
        public static string ShareSiteRenren {
            get {
                return ResourceManager.GetString("ShareSiteRenren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tencent Weibo 的本地化字符串。
        /// </summary>
        public static string ShareSiteTencentWeibo {
            get {
                return ResourceManager.GetString("ShareSiteTencentWeibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Twitter 的本地化字符串。
        /// </summary>
        public static string ShareSiteTwitter {
            get {
                return ResourceManager.GetString("ShareSiteTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sina Weibo 的本地化字符串。
        /// </summary>
        public static string ShareSiteWeibo {
            get {
                return ResourceManager.GetString("ShareSiteWeibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Share on Tencent Weibo 的本地化字符串。
        /// </summary>
        public static string ShareTencentWeibo {
            get {
                return ResourceManager.GetString("ShareTencentWeibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I&apos;m listening to {1} - {0} 的本地化字符串。
        /// </summary>
        public static string ShareText1 {
            get {
                return ResourceManager.GetString("ShareText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Share on Twitter 的本地化字符串。
        /// </summary>
        public static string ShareTwitter {
            get {
                return ResourceManager.GetString("ShareTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Share on Sina Weibo 的本地化字符串。
        /// </summary>
        public static string ShareWeibo {
            get {
                return ResourceManager.GetString("ShareWeibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error summary: 的本地化字符串。
        /// </summary>
        public static string ShortMessageTextBlock {
            get {
                return ResourceManager.GetString("ShortMessageTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Lyrics 的本地化字符串。
        /// </summary>
        public static string ShowLyrics {
            get {
                return ResourceManager.GetString("ShowLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Homepage 的本地化字符串。
        /// </summary>
        public static string SoftwareHome {
            get {
                return ResourceManager.GetString("SoftwareHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Justify 的本地化字符串。
        /// </summary>
        public static string StretchAlignment {
            get {
                return ResourceManager.GetString("StretchAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy successful 的本地化字符串。
        /// </summary>
        public static string SuccessfullyCopied {
            get {
                return ResourceManager.GetString("SuccessfullyCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logged in 的本地化字符串。
        /// </summary>
        public static string TheLoggedLabel {
            get {
                return ResourceManager.GetString("TheLoggedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A third-party client 的本地化字符串。
        /// </summary>
        public static string ThirdPartyClientsBlock {
            get {
                return ResourceManager.GetString("ThirdPartyClientsBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top 的本地化字符串。
        /// </summary>
        public static string TopAlignment {
            get {
                return ResourceManager.GetString("TopAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Played: {0} 的本地化字符串。
        /// </summary>
        public static string TotalFormatString {
            get {
                return ResourceManager.GetString("TotalFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto remove brackets and their contents 的本地化字符串。
        /// </summary>
        public static string TrimBracketsCheckBox {
            get {
                return ResourceManager.GetString("TrimBracketsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main UI font 的本地化字符串。
        /// </summary>
        public static string UISettingsWindowMainInterfaceFontTextBlock {
            get {
                return ResourceManager.GetString("UISettingsWindowMainInterfaceFontTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main UI scale 的本地化字符串。
        /// </summary>
        public static string UISettingsWindowMainInterfaceScaleTextBlock {
            get {
                return ResourceManager.GetString("UISettingsWindowMainInterfaceScaleTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Popup when switching to a new song 的本地化字符串。
        /// </summary>
        public static string UISettingsWindowPopupCb {
            get {
                return ResourceManager.GetString("UISettingsWindowPopupCb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window background 的本地化字符串。
        /// </summary>
        public static string UISettingsWindowWindowBackgroundGB {
            get {
                return ResourceManager.GetString("UISettingsWindowWindowBackgroundGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom color 的本地化字符串。
        /// </summary>
        public static string UISettingsWindowWindowManualColorCB {
            get {
                return ResourceManager.GetString("UISettingsWindowWindowManualColorCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spectrum 的本地化字符串。
        /// </summary>
        public static string UISettingsWindowWindowSpectrumCB {
            get {
                return ResourceManager.GetString("UISettingsWindowWindowSpectrumCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove from favorites 的本地化字符串。
        /// </summary>
        public static string UnfavoriteButton {
            get {
                return ResourceManager.GetString("UnfavoriteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel like 的本地化字符串。
        /// </summary>
        public static string UnlikeThumbButton {
            get {
                return ResourceManager.GetString("UnlikeThumbButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link copied to clipborad 的本地化字符串。
        /// </summary>
        public static string UrlCopyedToClipboard {
            get {
                return ResourceManager.GetString("UrlCopyedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your login status has expired 的本地化字符串。
        /// </summary>
        public static string UserExpiredCaption {
            get {
                return ResourceManager.GetString("UserExpiredCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your login status has expired. Please login again. 的本地化字符串。
        /// </summary>
        public static string UserExpiredMessage {
            get {
                return ResourceManager.GetString("UserExpiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please kindly explain what exactly you were doing. This will help me analyze the problem. 的本地化字符串。
        /// </summary>
        public static string UserMessageTextBlock {
            get {
                return ResourceManager.GetString("UserMessageTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username 的本地化字符串。
        /// </summary>
        public static string UserNameLabel {
            get {
                return ResourceManager.GetString("UserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Captcha 的本地化字符串。
        /// </summary>
        public static string VerificationCaptchaBlock {
            get {
                return ResourceManager.GetString("VerificationCaptchaBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View the error report 的本地化字符串。
        /// </summary>
        public static string ViewErrorMessageButton {
            get {
                return ResourceManager.GetString("ViewErrorMessageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DoubanFM 的本地化字符串。
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DoubanFM 的本地化字符串。
        /// </summary>
        public static string WindowTitleShort {
            get {
                return ResourceManager.GetString("WindowTitleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zip files 的本地化字符串。
        /// </summary>
        public static string ZipFileFilterName {
            get {
                return ResourceManager.GetString("ZipFileFilterName", resourceCulture);
            }
        }
    }
}
